### ISSUE TITLE
CASEN descriptives

### ISSUE THREAD

**Issue by Blopa88** [valentinaandrade/quantile-wage-gap#2]
Me demore un poco armando el panel y los graficos, pero esto salio:

Usando Ln Wages:

![image](https://github.com/valentinaandrade/quantile-wage-gap/assets/29583218/e619cfe6-64b0-4c23-8092-9636ea2e0de7)

Usando Ln hourly wages:

![image](https://github.com/valentinaandrade/quantile-wage-gap/assets/29583218/1a3c1c5e-9a62-443b-adc6-b02f40eabf4b)

*Impresiones: 

-El margen extensivo es super importante en la parte baja de la distribucion
-Con hourly wages (la medida estandar en labor) se ve el break en 2013 para algunos quintiles, bien claro solo en el primero. Esto me deja mas tranquilo en relacion a los datos de AFC. La restriccion de haber estado 12 meses continuos trabajando seguro esta ayudando con el problema del margen extensivo. La restriccion de minimum wages que mencione también nos puede ayudar.

*Dudas (@valentinaandrade):
- En este ejercicio yo estoy considerando el promedio within quintile de la distribucion especifica a cada genero. Con eso genero el gap. Es esto equivalente a lo que haces tu?
- Tienen alguna restriccion de edad? Es más o menos estándar mirar prime age workers (restringuir a trabajadores entre 30-50 años, o algo así).

El análisis con hourly wages por genero:

![image](https://github.com/valentinaandrade/quantile-wage-gap/assets/29583218/cd1beb7a-f077-443a-ae45-10b3887647eb)

![image](https://github.com/valentinaandrade/quantile-wage-gap/assets/29583218/68663f56-3984-4309-aa1e-46f0b554a2c0)

Al menos en estos datos no hay nada que salte a la vista para explicar el gap.

**Comment by valentinaandrade** [comment]
Hola @Blopa88 !

Muchísimas gracias por los ejercicios, fue muy rápido. 

1. Impresiones
- Que bien que el break se ve ve al menos para el quantile 10 que pusimos en el proposal. También se ve para el del 50 (es bastante abrupto). ¿Cómo es en el 90? Quizás en estos datos está mucho mas top-coded la distribución salarial. 

2. Dudas @valentinaandrade 
- Si, es equivalente. Yo saco el quantile 10, 50 y 90 por año y sexo (con collapse reduzco la dimensionalidad) y luego resto el quantile respectivo de hombres menos mujeres (ya que están en logaritmos)
- La unica restricción de edad que puse es la edad de jubilación (65 para hombres, 60 para mujeres)

3. Dudas @Blopa88 
- ¿Eliminaste a la gente bajo el minimum wage? ¿Los salarios son solo del empleo principal?
- ¿Qué intervalos de edad ocupaste?

Nuevamente gracias!!

Vale

**Comment by Blopa88** [comment]
Hice update del panel CASEN, considerando solo ingresos de la ocupacion principal. En base a los nuevos resultados que discutimos en la reunion de hoy, me enfoque en percentil 20 50 y 80. Abajo los resultados:

Log Wages

![image](https://github.com/valentinaandrade/quantile-wage-gap/assets/29583218/5e7ebf4b-0ce1-48d1-98c5-e61835d5489e)

Log Hourly Wages

![image](https://github.com/valentinaandrade/quantile-wage-gap/assets/29583218/dd0c44f9-5d30-4758-ad9f-cd553ed4cacc)

En ambos casos se ve un crecimiento y luego disminución de la brecha. 

*Muchas de las restricciones de AFC no son implementables en CASEN, e.g., condicionar en haber trabajado los ultimos 12 meses.

**Comment by valentinaandrade** [comment]
Buenísimos gráficos @Blopa88 !

Está super que se pueda descartar que lo que vemos con los datos tenga que ver con el margen intensivo. A mi me asustaba también eso porque en #5 veíamos que los parciales eran los que estaba aumentando su registro en el UI. Pero como también hablamos hoy no tenemos una aproximación certera a cómo son sus salarios. 

No creo que la restricción de la cotización de 12 meses sea muy binding aquí porque les preguntan por el empleo principal (que es lo que nosotros "tratamos" de aproximar). 

Lo que me gusta mucho  de esto es que hay un cambio de tendencia en las brechas salariales y que en el gráfico con salarios por hora se una tendencia diferenciada por quantiles (similar a la de la figura que se le ocurrió al profe @tommyrau )

![image](https://github.com/valentinaandrade/quantile-wage-gap/assets/56052549/97de4317-2239-488a-921c-228bd6f66798)

Básicamente, en el 20 hay una caída de la brecha salarial,  así como en la del 10 de la figura del proposal. Mientras que en 80 y 50 hay un aumento, y luego caída.  

Lo que no me gusta es que no tenemos una explicación o historia 😂 Me desorienta un poco en cómo seguir


-----------------------------------------------------------------------------------------------------------------------

PD gigante. Hay dos medidas que uno puede estudiar de sindicatos by gender: membresía sindical (numero de socios por sexo / total de socios) y tasa de sindicalización (sindicalizadas/ fuerza de trabajo factible de ser sindicalizada). 

La segunda es la que yo había estudiado y veía que el 2015-2016 la tasa de sindicalización supera a la masculina. Pero ahora saqué la membresía sindical y miren: está aumentando la femenina hasta el 2015 y después hay una caída post reforma laboral (que tenía como uno de sus propósitos aumentar la equidad de genero en la negociación colectiva jaja. But the way,  entre 2010 a 2015 se produce una importante reducción en el gap de mujeres en los sindicatos. Que lastima que aun no podemos pegar estos datos pero está muy bacan :-( 

<img width="1432" alt="image" src="https://github.com/valentinaandrade/quantile-wage-gap/assets/56052549/f3e3dcde-db72-4e52-92d8-bd7025f97389">

**Comment by Blopa88** [comment]
Claro, el patron en CASEN es similar a lo que tenian y ademas nos dice que no es solo una historia de margen intensivo (+ ya vimos que tampoco parece ser una historia de informalidad). Pero estoy igual, metido con que explica el patron en los datos.

**Comment by valentinaandrade** [comment]
I think the tasks related to this are done. Thanks, @Blopa88 for the insights! 💯
